### ISSUE TITLE
person_add_requests email is sent to people with no hitobito access.

### ISSUE THREAD

**Issue by gamba** [hitobito/hitobito#109]
When an authorisation request is generated (e.g. for adding an unknown person to an event), an automatic email is sent to the people that could authorise the request according to their role.

The email is sent to people without a valid/active login to hitobito (Midata in my case), too. These people shouldn't receive this type of emails as long they do not have a valid login to hitobito.

**Comment by RolandStuder** [comment]
Yeah, that should not happen, thanks for making us aware of it.

You can configure, which people receive an email. In the Tab "Anfragen" you can select who should be notified and who shouldn't. 

If we resolve this, we have to make sure, that everything is clear on the configuration view. It should not happen, that people look like they might get an Email because they are selected, but then receive none.

**Comment by gamba** [comment]
I agree. 

There are two types of people (with the right role authorise there actions): without and with a valid account. 
There are two types of settings for these people: the ones who receive the notifications, the ones who don't.

**Comment by RolandStuder** [comment]
Minor issue, probably wont'f fix this because of limited resources.
