### ISSUE TITLE
PERSON: Daten via API vs JSON+Token inkonsistent

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1460]
## Aktuelles Verhalten

Wenn ich einen User per API-Key aufrufe, fehlen einige Felder, die im User Token verfügbar sind.

Beispiel: https://pbs.puzzle.ch/de/groups/1/people/2.json?token=TOKEN

Es fehlen:

- Geburtsdatum
- Geschlecht
- Evtl. weitere?

## Gewünschtes Verhalten

Die Daten sollten gleich sein.

## Schritte zum reproduzieren

1. User per API aufrufen
2. Privates Fenster im Browser öffnen, um die Berechtigungen aufs Token zu isolieren
3. User direkt mit TOKEN aufrufen
4. Daten vergleichen

## How to fix
This data can be made available with the following additional ability in the method `define_person_abilities` in [token_ability.rb](https://github.com/hitobito/hitobito/blob/master/app/abilities/token_ability.rb):
```ruby
    can :show_details, Person do |p|
      Role.where(person: p, group: groups).present? &&
        Ability.new(token.dynamic_user).can?(:show_details, p)
    end
```
The details (birthday and gender) will then only appear in the API response of a single person (`/people/1.json`) and not in the list of people in a group (`/people.json`). This is all prepared, the only thing missing is the ability.

**Comment by Michael-Schaer** [comment]
Vielleicht vor Schritt 2 noch: `Privates Fenster im Browser öffnen, um die Berechtigungen aufs Token zu isolieren`

**Comment by Iomys** [comment]
Do we have any news about the progress of the issue? It is not practical to use the old way with the Personal API tokens which are deprecated.

**Comment by carlobeltrame** [comment]
> Do we have any news about the progress of the issue? It is not practical to use the old way with the Personal API tokens which are deprecated.

So far this hasn't been prioritized and paid for by CEVI nor PBS, so development at Puzzle hasn't started. Contributions are welcome of course.

See also the related issues https://github.com/hitobito/hitobito_pbs/issues/117 and https://github.com/hitobito/hitobito_pbs/issues/193 where I already detailed two different ways to get the birth date into the API response some time ago. Since there is the need for both birthday and gender in the API response, I would go for the fix from the first ticket (second bullet point in the list).

If you want to contribute but don't know how to start, the next PBS hackathon is in September: https://db.scout.ch/de/groups/9325/events/20441.html There we will be able to support you in setting up your development environment and in developing the feature. If you want to start earlier, we use Docker and [this repository](https://github.com/hitobito/development) to develop hitobito.
